apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: demo-basic-commands
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome</title>
    </head>
    <body>
      <h1>SPM -Kubernetes Session!</h1>
    </body>
    </html>