apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: demo-basic-commands
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Live Update</title>
    </head>
    <body>
      <h1>Live Update Successful! Kubernetes Makes Dynamic Scaling and Updates Easy!</h1>
    </body>
    </html>